function [D0,D1,D2,D3,D4,D5,D6,D7]=DEMUX1TO8(in,S2,S1,S0)
    D0=ANDGATE(ANDGATE(ANDGATE(NOTGATE(S0),NOTGATE(S1)),NOTGATE(S2)),in);
    D1=ANDGATE(ANDGATE(ANDGATE(S0,NOTGATE(S1)),NOTGATE(S2)),in);
    D2=ANDGATE(ANDGATE(ANDGATE(NOTGATE(S0),S1),NOTGATE(S2)),in);
    D3=ANDGATE(ANDGATE(ANDGATE(S0,S1),NOTGATE(S2)),in);
    D4=ANDGATE(ANDGATE(ANDGATE(NOTGATE(S0),NOTGATE(S1)),S2),in);
    D5=ANDGATE(ANDGATE(ANDGATE(S0,NOTGATE(S1)),S2),in);
    D6=ANDGATE(ANDGATE(ANDGATE(NOTGATE(S0),S1),S2),in);
    D7=ANDGATE(ANDGATE(ANDGATE(S0,S1),S2),in);
end